// Client-safe pure function. Does NOT import the Groq SDK.
// Keep this in its own module so client components can import it without
// pulling server-only code into the browser bundle.

function normalize(s: string): string {
  return (s || "").trim().toLowerCase().replace(/[^a-z0-9]/g, "");
}

function stemEqual(a: string, b: string): boolean {
  if (!a || !b) return false;
  if (a === b) return true;
  // Tolerate simple morphological variants: plural, -ing, -ed, -es, -er
  const variants = (w: string) => [
    w,
    w.replace(/ies$/, "y"),
    w.replace(/es$/, ""),
    w.replace(/s$/, ""),
    w.replace(/ing$/, ""),
    w.replace(/ing$/, "e"),
    w.replace(/ed$/, ""),
    w.replace(/ed$/, "e"),
    w.replace(/er$/, ""),
    w.replace(/er$/, "e"),
  ];
  const va = new Set(variants(a));
  const vb = new Set(variants(b));
  for (const x of va) if (vb.has(x)) return true;
  return false;
}

/**
 * Context-aware fill-in-the-blank evaluation.
 * Accepts the primary correct answer OR any of the `accepted_answers`
 * synonyms/contextual alternates generated by the AI.
 */
export function evaluateFillBlank(
  userAnswer: string,
  correctAnswer: string,
  acceptedAnswers: string[] = []
): boolean {
  const u = normalize(userAnswer);
  const c = normalize(correctAnswer);
  if (!u) return false;
  if (stemEqual(u, c)) return true;
  for (const a of acceptedAnswers || []) {
    if (stemEqual(u, normalize(a))) return true;
  }
  return false;
}